## Configuration for the STARsolo_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################

## ~~~~~ sample sheet ~~~~~
### See `example_sample_sheet.csv` for details
# SAMPLE_SHEET_PATH: /nfs/home/dmckellar/private_utils/sample_sheets/visium/CS001-5.csv
SAMPLE_SHEET_PATH: /nfs/home/dmckellar/private_utils/sample_sheets/visium/vy3.csv

# STARsolo parameters
CORES: 8 # how many cores to give each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 127000000000  # limit in bytes
MEMLIMIT_MB: 127000     # limit in megabytes
MEMLIMIT_GB: 127G       # mem limit for kallisto

## Recipe details (whitelists, barcode/UMI design, etc.)
RECIPE_SHEET: resources/recipe_sheet.csv

########################################################################################################
# Important directory file paths
########################################################################################################
# **Change these paths for where you want temporary (TMPDIR) and output (OUTDIR) files
#TODO: add OUTDIR to sample sheet
TMPDIR: ./tmp
OUTDIR: /gpfs/commons/groups/innovation/dwm/ontxg/data/slide_out

########################################################################################################
# Executables - file paths
########################################################################################################
EXEC:
  BLASTN: blastn
  BWA: bwa
  BOWTIE2: bowtie2
  BUSTOOLS: bustools 
  CUTADAPT: cutadapt 
  FASTQC: fastqc 
  KALLISTO: kallisto
  MIRGE: miRge3.0
  PIGZ: pigz
  QUALIMAP: qualimap
  SAMTOOLS: samtools
  STAR: STAR 
  UMITOOLS: umi_tools
  FASTX_COLLAPSER: fastx_collapser

########################################################################################################
# Resources - file paths
########################################################################################################
FASTQC_ADAPTERS: resources/fastqc_adapters.txt 
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored
MIRGE_LIB: /home/dwm269/usr/bin/miRge3_Lib

########################################################################################################
# Library details
########################################################################################################
R1_INTERNAL_ADAPTER: "TCTTCAGCGTTCCCGAGA" # internal R1 adapter between slideseq barcodes
piRNA_INDEX: '/workdir/dwm269/genomes/pirbase/mmu/gold/bowtie2/index' # bowtie2 index of piRNAs; just mouse implemented now...
MAX_SHORT_READ_LENGTH: 34 # max read length for reads to be aligned to short RNA references