## Configuration for the STARsolo_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################

# Sample sheet requires a sampleID, and locations of fastqs for R1 and R2
#     For multi-lane inputs, use the following format (from STARsolo github page):
#       --readFilesIn Read2_Lane1.fastq.gz,Read2_Lane2.fastq.gz,Read2_Lane3.fastq.gz  Read1_Lane1.fastq.gz,Read1_Lane2.fastq.gz,Read1_Lane3.fastq.gz

## ~~~~~ sample sheets ~~~~~
SAMPLE_SHEET_PATH: /path/to/sample_sheet.csv

# STARsolo parameters
CORES: 24 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 200000000000  # limit in bytes
MEMLIMIT_GB: 300G       # mem limit for kallisto

## Recipe details (whitelists, barcode/UMI design, etc.)
RECIPE_SHEET: resources/recipe_sheet.csv

########################################################################################################
# Important directory file paths
########################################################################################################
# **Change these paths for where you want temporary (TMPDIR) and output (OUTDIR) files
#TODO: add OUTDIR to sample sheet
TMPDIR: ./tmp
OUTDIR: ./data/align_out

########################################################################################################
# Executables - file paths
########################################################################################################
BWA_EXEC: bwa
STAR_EXEC: STAR 
KALLISTO_EXEC: kallisto
BUST_EXEC: bustools 
CUTADAPT_EXEC: cutadapt 
FASTQC_EXEC: fastqc 
SAMTOOLS_EXEC: samtools
UMITOOLS_EXEC: umi_tools
QUALIMAP_EXEC: qualimap
MIRGE_EXEC: miRge3.0
BAM2SPLITBW: /home/dwm269/DWM_utils/seq_utils/bam2splitBigWig.sh #Custom function in DWM_utils that splits a bam file by strand and converts it into bigwig format
FASTX_COLLAPSER: fastx_collapser
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

########################################################################################################
# Resources - file paths
########################################################################################################
FASTQC_ADAPTERS: resources/fastqc_adapters.txt 
MIRGE_LIB: /home/dwm269/usr/bin/miRge3_Lib

########################################################################################################
# Library details
########################################################################################################
R1_INTERNAL_ADAPTER: "TCTTCAGCGTTCCCGAGA"
MAX_SHORT_READ_LENGTH: 34